### ISSUE TITLE
Linking(?) issue when using find_package after installation

### ISSUE THREAD

**Issue by s1m0n-f** [offa/influxdb-cxx#201]
### Issue
After building and installing both cpr and influxdb-cxx i get the following error if I build and run the test_package example.
> ./test_package: error while loading shared libraries: libcpr.so.1: cannot open shared object file: No such file or directory

Even though the file exists and cpr works on its own.
### Details
I've been struggling with this issue for a while and I don't understand why it occurs. I'm running a 64bit Ubuntu 22.04 LTS VM on a Windows host. I'm building and installing cpr as described in their repo with the flag CPR_USE_SYSTEM_CURL=ON.

I'm building this library with the flags INFLUXCXX_TESTING=OFF and INFLUXCXX_WITH_BOOST=OFF

I've tried with the latest master of both cpr and influxdb-cxx as well as cpr 1.10.0 together with influxdb-cxx v0.7.1 with the same outcome. If I try to build and run a similar minimalistic example using just cpr, that works fine which is why I believe that the issue isn't with cpr.

By coincidence I noticed that if I make an example that includes and uses cpr as well as influxdb-cxx it runs without the error, so something is not working when l just use influxdb-cxx in the project.

I might be missing something obvious, let me know if there's any more details needed.

For a minimal example that runs and doesn't give the error:
CMakeLists.txt:
```
cmake_minimum_required(VERSION 3.12)
project(test_package CXX)

find_package(InfluxDB REQUIRED)
find_package(cpr REQUIRED)

add_executable(test_package example.cpp)
target_link_libraries(test_package PRIVATE InfluxData::InfluxDB)
target_link_libraries(test_package PRIVATE cpr::cpr)
target_compile_features(test_package PRIVATE cxx_std_17)
```

example.cpp:
```
#include <InfluxDBFactory.h>
#include "cpr/cpr.h"

int main()
{    
    auto influxdb = influxdb::InfluxDBFactory::Get("http://localhost:8086?db=test");
    influxdb->addGlobalTag("test", "value");
    
    cpr::Response r = cpr::Get(cpr::Url{"https://api.github.com/repos/whoshuu/cpr/contributors"},
                               cpr::Authentication{"user", "pass", cpr::AuthMode::BASIC},
                               cpr::Parameters{{"anon", "true"}, {"key", "value"}});
}
```

**Comment by offa** [comment]
> After building and installing both cpr and influxdb-cxx i get the following error if I build and run the test_package example.

Marginally: The `test_package` directory is used for Conan packaging tests.

> By coincidence I noticed that if I make an example that includes and uses cpr as well as influxdb-cxx it runs without the error, so something is not working when l just use influxdb-cxx in the project.

If you build the example without the cpr code in both listings, what is the error you get? Also can you verify whether cpr has installed it's cmake files correctly (either listed on `make install` or available on the filesystem).

**Comment by offa** [comment]
Update: I was able to reproduce the issue using these steps:

```bash
#!/bin/bash

set -ex

BASE_PATH="/tmp/ifdbcxx_repro"

rm -rf "${BASE_PATH}"
mkdir -p "${BASE_PATH}"
cd "${BASE_PATH}"

git clone --depth=1 -b 1.10.4 https://github.com/libcpr/cpr.git
mkdir -p cpr/build
cd cpr/build

cmake -DCPR_USE_SYSTEM_CURL=ON -DCMAKE_INSTALL_PREFIX="${BASE_PATH}/deps" ..
cmake --build . -j
cmake --build . --target install

cd "${BASE_PATH}"

git clone --depth=1 https://github.com/offa/influxdb-cxx.git
mkdir -p influxdb-cxx/build
cd influxdb-cxx/build

cmake -DINFLUXCXX_TESTING=OFF -DINFLUXCXX_WITH_BOOST=OFF -Dcpr_DIR="${BASE_PATH}/deps/lib/cmake/cpr/" -DCMAKE_INSTALL_PREFIX="${BASE_PATH}/deps" ..
cmake --build . -j
cmake --build . --target install

cd "${BASE_PATH}/influxdb-cxx/test_package"
mkdir build
cd build

cmake -DInfluxDB_DIR="${BASE_PATH}/deps/lib/cmake/InfluxDB/" -Dcpr_DIR="${BASE_PATH}/deps/lib/cmake/cpr/" ..
cmake --build . -j
./test_package
```

**Comment by K9Megahertz** [comment]
Well that seemed to work.

Fresh install of ubuntu 20.04

apt-get install git
apt-get install cmake
apt-get install build-essential
apt-get install openssl
apt-get install libssl-dev
apt-get install curl
apt-get install libcurl4-openssl-dev



root@dev03:~# ./test.sh
+ BASE_PATH=/tmp/ifdbcxx_repro
+ rm -rf /tmp/ifdbcxx_repro
+ mkdir -p /tmp/ifdbcxx_repro
+ cd /tmp/ifdbcxx_repro
+ git clone --depth=1 -b 1.10.4 https://github.com/libcpr/cpr.git
Cloning into 'cpr'...
remote: Enumerating objects: 189, done.
remote: Counting objects: 100% (189/189), done.
remote: Compressing objects: 100% (178/178), done.
remote: Total 189 (delta 21), reused 77 (delta 5), pack-reused 0
Receiving objects: 100% (189/189), 153.87 KiB | 2.65 MiB/s, done.
Resolving deltas: 100% (21/21), done.
Note: switching to '2553fc41450301cd09a9271c8d2c3e0cf3546b73'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

+ mkdir -p cpr/build
+ cd cpr/build
+ cmake -DCPR_USE_SYSTEM_CURL=ON -DCMAKE_INSTALL_PREFIX=/tmp/ifdbcxx_repro/deps ..
-- The CXX compiler identification is GNU 9.4.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CXX standard: 17
-- C++ Requests CMake Options
-- =======================================================
--   CPR_GENERATE_COVERAGE: OFF
--   CPR_CURL_NOSIGNAL: OFF
--   CURL_VERBOSE_LOGGING: OFF
--   CPR_USE_SYSTEM_GTEST: OFF
--   CPR_USE_SYSTEM_CURL: ON
--   CPR_ENABLE_CURL_HTTP_ONLY: ON
--   CPR_ENABLE_SSL: ON
--   CPR_FORCE_OPENSSL_BACKEND: OFF
--   CPR_FORCE_WINSSL_BACKEND: OFF
--   CPR_FORCE_DARWINSSL_BACKEND: OFF
--   CPR_FORCE_MBEDTLS_BACKEND: OFF
--   CPR_ENABLE_LINTING: OFF
--   CPR_ENABLE_CPPCHECK: OFF
--   CPR_BUILD_TESTS: OFF
--   CPR_BUILD_TESTS_SSL: OFF
--   CPR_BUILD_TESTS_PROXY: OFF
--   CPR_SKIP_CA_BUNDLE_SEARCH: OFF
--   CPR_USE_BOOST_FILESYSTEM: OFF
--   CPR_DEBUG_SANITIZER_FLAG_THREAD: OFF
--   CPR_DEBUG_SANITIZER_FLAG_ADDR: OFF
--   CPR_DEBUG_SANITIZER_FLAG_LEAK: OFF
--   CPR_DEBUG_SANITIZER_FLAG_UB: OFF
--   CPR_DEBUG_SANITIZER_FLAG_ALL: OFF
-- =======================================================
-- Performing Test THREAD_SANITIZER_AVAILABLE
-- Performing Test THREAD_SANITIZER_AVAILABLE - Success
-- Performing Test ADDRESS_SANITIZER_AVAILABLE
-- Performing Test ADDRESS_SANITIZER_AVAILABLE - Success
-- Performing Test LEAK_SANITIZER_AVAILABLE
-- Performing Test LEAK_SANITIZER_AVAILABLE - Success
-- Performing Test UNDEFINED_BEHAVIOUR_SANITIZER_AVAILABLE
-- Performing Test UNDEFINED_BEHAVIOUR_SANITIZER_AVAILABLE - Success
-- Performing Test ALL_SANITIZERS_AVAILABLE
-- Performing Test ALL_SANITIZERS_AVAILABLE - Success
-- Automatically detecting SSL backend.
-- Detecting SSL backend...
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.1.1f")
-- SSL auto detect: Using OpenSSL.
-- Found CURL: /usr/lib/x86_64-linux-gnu/libcurl.so (found version "7.68.0") found components: HTTP HTTPS
-- Curl 7.68.0 found on this system.
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/ifdbcxx_repro/cpr/build
+ cmake --build . -j
Scanning dependencies of target cpr
[  3%] Building CXX object cpr/CMakeFiles/cpr.dir/accept_encoding.cpp.o
[  6%] Building CXX object cpr/CMakeFiles/cpr.dir/callback.cpp.o
[ 10%] Building CXX object cpr/CMakeFiles/cpr.dir/async.cpp.o
[ 13%] Building CXX object cpr/CMakeFiles/cpr.dir/auth.cpp.o
[ 17%] Building CXX object cpr/CMakeFiles/cpr.dir/bearer.cpp.o
[ 20%] Building CXX object cpr/CMakeFiles/cpr.dir/cert_info.cpp.o
[ 24%] Building CXX object cpr/CMakeFiles/cpr.dir/cookies.cpp.o
[ 27%] Building CXX object cpr/CMakeFiles/cpr.dir/cprtypes.cpp.o
[ 31%] Building CXX object cpr/CMakeFiles/cpr.dir/curlholder.cpp.o
[ 34%] Building CXX object cpr/CMakeFiles/cpr.dir/curl_container.cpp.o
[ 37%] Building CXX object cpr/CMakeFiles/cpr.dir/multipart.cpp.o
[ 41%] Building CXX object cpr/CMakeFiles/cpr.dir/error.cpp.o
[ 44%] Building CXX object cpr/CMakeFiles/cpr.dir/file.cpp.o
[ 48%] Building CXX object cpr/CMakeFiles/cpr.dir/parameters.cpp.o
[ 51%] Building CXX object cpr/CMakeFiles/cpr.dir/payload.cpp.o
[ 55%] Building CXX object cpr/CMakeFiles/cpr.dir/proxies.cpp.o
[ 58%] Building CXX object cpr/CMakeFiles/cpr.dir/session.cpp.o
[ 62%] Building CXX object cpr/CMakeFiles/cpr.dir/proxyauth.cpp.o
[ 65%] Building CXX object cpr/CMakeFiles/cpr.dir/timeout.cpp.o
[ 68%] Building CXX object cpr/CMakeFiles/cpr.dir/threadpool.cpp.o
[ 72%] Building CXX object cpr/CMakeFiles/cpr.dir/util.cpp.o
[ 75%] Building CXX object cpr/CMakeFiles/cpr.dir/unix_socket.cpp.o
[ 79%] Building CXX object cpr/CMakeFiles/cpr.dir/response.cpp.o
[ 82%] Building CXX object cpr/CMakeFiles/cpr.dir/redirect.cpp.o
[ 86%] Building CXX object cpr/CMakeFiles/cpr.dir/ssl_ctx.cpp.o
[ 89%] Building CXX object cpr/CMakeFiles/cpr.dir/curlmultiholder.cpp.o
[ 93%] Building CXX object cpr/CMakeFiles/cpr.dir/interceptor.cpp.o
[ 96%] Building CXX object cpr/CMakeFiles/cpr.dir/multiperform.cpp.o
[100%] Linking CXX shared library ../lib/libcpr.so
[100%] Built target cpr
+ cmake --build . --target install
[100%] Built target cpr
Install the project...
-- Install configuration: ""
-- Installing: /tmp/ifdbcxx_repro/deps/lib/libcpr.so.1.10.4
-- Installing: /tmp/ifdbcxx_repro/deps/lib/libcpr.so.1
-- Installing: /tmp/ifdbcxx_repro/deps/lib/libcpr.so
-- Installing: /tmp/ifdbcxx_repro/deps/lib/cmake/cpr/cprTargets.cmake
-- Installing: /tmp/ifdbcxx_repro/deps/lib/cmake/cpr/cprTargets-noconfig.cmake
-- Installing: /tmp/ifdbcxx_repro/deps/lib/cmake/cpr/cprConfig.cmake
-- Installing: /tmp/ifdbcxx_repro/deps/lib/cmake/cpr/cprConfigVersion.cmake
-- Installing: /tmp/ifdbcxx_repro/deps/include/cpr
-- Installing: /tmp/ifdbcxx_repro/deps/include/cpr/local_port.h
-- Installing: /tmp/ifdbcxx_repro/deps/include/cpr/callback.h
-- Installing: /tmp/ifdbcxx_repro/deps/include/cpr/proxies.h
-- Installing: /tmp/ifdbcxx_repro/deps/include/cpr/api.h
-- Installing: /tmp/ifdbcxx_repro/deps/include/cpr/buffer.h
-- Installing: /tmp/ifdbcxx_repro/deps/include/cpr/multiperform.h
-- Installing: /tmp/ifdbcxx_repro/deps/include/cpr/curlholder.h
-- Installing: /tmp/ifdbcxx_repro/deps/include/cpr/redirect.h
-- Installing: /tmp/ifdbcxx_repro/deps/include/cpr/resolve.h
-- Installing: /tmp/ifdbcxx_repro/deps/include/cpr/cookies.h
-- Installing: /tmp/ifdbcxx_repro/deps/include/cpr/threadpool.h
-- Installing: /tmp/ifdbcxx_repro/deps/include/cpr/parameters.h
-- Installing: /tmp/ifdbcxx_repro/deps/include/cpr/auth.h
-- Installing: /tmp/ifdbcxx_repro/deps/include/cpr/response.h
-- Installing: /tmp/ifdbcxx_repro/deps/include/cpr/limit_rate.h
-- Installing: /tmp/ifdbcxx_repro/deps/include/cpr/unix_socket.h
-- Installing: /tmp/ifdbcxx_repro/deps/include/cpr/session.h
-- Installing: /tmp/ifdbcxx_repro/deps/include/cpr/cpr.h
-- Installing: /tmp/ifdbcxx_repro/deps/include/cpr/payload.h
-- Installing: /tmp/ifdbcxx_repro/deps/include/cpr/util.h
-- Installing: /tmp/ifdbcxx_repro/deps/include/cpr/multipart.h
-- Installing: /tmp/ifdbcxx_repro/deps/include/cpr/cert_info.h
-- Installing: /tmp/ifdbcxx_repro/deps/include/cpr/http_version.h
-- Installing: /tmp/ifdbcxx_repro/deps/include/cpr/local_port_range.h
-- Installing: /tmp/ifdbcxx_repro/deps/include/cpr/user_agent.h
-- Installing: /tmp/ifdbcxx_repro/deps/include/cpr/cprtypes.h
-- Installing: /tmp/ifdbcxx_repro/deps/include/cpr/filesystem.h
-- Installing: /tmp/ifdbcxx_repro/deps/include/cpr/async_wrapper.h
-- Installing: /tmp/ifdbcxx_repro/deps/include/cpr/curl_container.h
-- Installing: /tmp/ifdbcxx_repro/deps/include/cpr/status_codes.h
-- Installing: /tmp/ifdbcxx_repro/deps/include/cpr/low_speed.h
-- Installing: /tmp/ifdbcxx_repro/deps/include/cpr/ssl_ctx.h
-- Installing: /tmp/ifdbcxx_repro/deps/include/cpr/bearer.h
-- Installing: /tmp/ifdbcxx_repro/deps/include/cpr/range.h
-- Installing: /tmp/ifdbcxx_repro/deps/include/cpr/ssl_options.h
-- Installing: /tmp/ifdbcxx_repro/deps/include/cpr/file.h
-- Installing: /tmp/ifdbcxx_repro/deps/include/cpr/proxyauth.h
-- Installing: /tmp/ifdbcxx_repro/deps/include/cpr/error.h
-- Installing: /tmp/ifdbcxx_repro/deps/include/cpr/async.h
-- Installing: /tmp/ifdbcxx_repro/deps/include/cpr/interface.h
-- Installing: /tmp/ifdbcxx_repro/deps/include/cpr/accept_encoding.h
-- Installing: /tmp/ifdbcxx_repro/deps/include/cpr/connect_timeout.h
-- Installing: /tmp/ifdbcxx_repro/deps/include/cpr/curlmultiholder.h
-- Installing: /tmp/ifdbcxx_repro/deps/include/cpr/interceptor.h
-- Installing: /tmp/ifdbcxx_repro/deps/include/cpr/reserve_size.h
-- Installing: /tmp/ifdbcxx_repro/deps/include/cpr/singleton.h
-- Installing: /tmp/ifdbcxx_repro/deps/include/cpr/body.h
-- Installing: /tmp/ifdbcxx_repro/deps/include/cpr/verbose.h
-- Installing: /tmp/ifdbcxx_repro/deps/include/cpr/timeout.h
-- Up-to-date: /tmp/ifdbcxx_repro/deps/include/cpr
-- Installing: /tmp/ifdbcxx_repro/deps/include/cpr/cprver.h
+ cd /tmp/ifdbcxx_repro
+ git clone --depth=1 https://github.com/offa/influxdb-cxx.git
Cloning into 'influxdb-cxx'...
remote: Enumerating objects: 81, done.
remote: Counting objects: 100% (81/81), done.
remote: Compressing objects: 100% (77/77), done.
remote: Total 81 (delta 19), reused 24 (delta 2), pack-reused 0
Unpacking objects: 100% (81/81), 83.56 KiB | 1.16 MiB/s, done.
+ mkdir -p influxdb-cxx/build
+ cd influxdb-cxx/build
+ cmake -DINFLUXCXX_TESTING=OFF -DINFLUXCXX_WITH_BOOST=OFF -Dcpr_DIR=/tmp/ifdbcxx_repro/deps/lib/cmake/cpr/ -DCMAKE_INSTALL_PREFIX=/tmp/ifdbcxx_repro/deps ..
-- The CXX compiler identification is GNU 9.4.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- ~~~ influxdb-cxx v0.7.1 ~~~
-- Build Type : RelWithDebInfo
-- Boost support : OFF
-- Unit Tests : OFF
-- System Tests : ON
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found CURL: /usr/lib/x86_64-linux-gnu/libcurl.so (found version "7.68.0")
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/ifdbcxx_repro/influxdb-cxx/build
+ cmake --build . -j
Scanning dependencies of target InfluxDB-BoostSupport
Scanning dependencies of target InfluxDB-Internal
Scanning dependencies of target InfluxDB-Core
[ 12%] Building CXX object src/CMakeFiles/InfluxDB-BoostSupport.dir/NoBoostSupport.cxx.o
[ 37%] Building CXX object src/CMakeFiles/InfluxDB-Internal.dir/LineProtocol.cxx.o
[ 37%] Building CXX object src/CMakeFiles/InfluxDB-Internal.dir/HTTP.cxx.o
[ 50%] Building CXX object src/CMakeFiles/InfluxDB-Core.dir/Point.cxx.o
[ 62%] Building CXX object src/CMakeFiles/InfluxDB-Core.dir/InfluxDB.cxx.o
[ 87%] Building CXX object src/CMakeFiles/InfluxDB-Core.dir/InfluxDBFactory.cxx.o
[ 87%] Building CXX object src/CMakeFiles/InfluxDB-Core.dir/Proxy.cxx.o
[ 87%] Built target InfluxDB-BoostSupport
[ 87%] Built target InfluxDB-Core
[ 87%] Built target InfluxDB-Internal
Scanning dependencies of target InfluxDB
[100%] Linking CXX shared library libInfluxDB.so
[100%] Built target InfluxDB
+ cmake --build . --target install
[ 50%] Built target InfluxDB-Core
[ 62%] Built target InfluxDB-BoostSupport
[ 87%] Built target InfluxDB-Internal
[100%] Built target InfluxDB
Install the project...
-- Install configuration: "RelWithDebInfo"
-- Installing: /tmp/ifdbcxx_repro/deps/lib/libInfluxDB.so.1.0.0
-- Installing: /tmp/ifdbcxx_repro/deps/lib/libInfluxDB.so.1
-- Set runtime path of "/tmp/ifdbcxx_repro/deps/lib/libInfluxDB.so.1.0.0" to ""
-- Installing: /tmp/ifdbcxx_repro/deps/lib/libInfluxDB.so
-- Up-to-date: /tmp/ifdbcxx_repro/deps/include
-- Installing: /tmp/ifdbcxx_repro/deps/include/Proxy.h
-- Installing: /tmp/ifdbcxx_repro/deps/include/Point.h
-- Installing: /tmp/ifdbcxx_repro/deps/include/InfluxDB.h
-- Installing: /tmp/ifdbcxx_repro/deps/include/InfluxDBException.h
-- Installing: /tmp/ifdbcxx_repro/deps/include/InfluxDBFactory.h
-- Installing: /tmp/ifdbcxx_repro/deps/include/Transport.h
-- Installing: /tmp/ifdbcxx_repro/deps/include/influxdb_export.h
-- Installing: /tmp/ifdbcxx_repro/deps/lib/cmake/InfluxDB/InfluxDBTargets.cmake
-- Installing: /tmp/ifdbcxx_repro/deps/lib/cmake/InfluxDB/InfluxDBTargets-relwithdebinfo.cmake
-- Installing: /tmp/ifdbcxx_repro/deps/lib/cmake/InfluxDB/InfluxDBConfig.cmake
-- Installing: /tmp/ifdbcxx_repro/deps/lib/cmake/InfluxDB/InfluxDBConfigVersion.cmake
+ cd /tmp/ifdbcxx_repro/influxdb-cxx/test_package
+ mkdir build
+ cd build
+ cmake -DInfluxDB_DIR=/tmp/ifdbcxx_repro/deps/lib/cmake/InfluxDB/ -Dcpr_DIR=/tmp/ifdbcxx_repro/deps/lib/cmake/cpr/ ..
-- The CXX compiler identification is GNU 9.4.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found CURL: /usr/lib/x86_64-linux-gnu/libcurl.so (found version "7.68.0")
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- InfluxDB 0.7.1 found
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/ifdbcxx_repro/influxdb-cxx/test_package/build
+ cmake --build . -j
Scanning dependencies of target test_package
[ 50%] Building CXX object CMakeFiles/test_package.dir/example.cpp.o
[100%] Linking CXX executable test_package
[100%] Built target test_package

**Comment by offa** [comment]
> Well that seemed to work.

But the final call to test_package fails due to a missing cpr SO, right?
At least that's the error I can reproduce.

**Comment by K9Megahertz** [comment]
Yes, I do get that error when trying to run it. 

./test_package: error while loading shared libraries: libcpr.so.1: cannot open shared object file: No such file or directory
root@dev03:/tmp/ifdbcxx_repro/influxdb-cxx/test_package/build#

**Comment by offa** [comment]
I have pushed a fix to `201-cpr_so_linking` branch, could you give it a try please?

--> The script above works and `ldd` shows correct results.

**Comment by s1m0n-f** [comment]
Hello, thanks for looking into it!

Tried running your script but still get the same error on a clean Ubuntu install. Added "-b 201-cpr_so_linking" in the git clone command so it checks out the correct commit. Seems strange that it works for you but not me since you could reproduce the error before. I checked the CMakeLists.txt in src and it had the changes you made so seems like something is still not working.

```
simon@simon-VirtualBox:/tmp/ifdbcxx_repro/influxdb-cxx/test_package/build$ ldd test_package
	linux-vdso.so.1 (0x00007ffdc57e9000)
	libInfluxDB.so.1 => /tmp/ifdbcxx_repro/deps/lib/libInfluxDB.so.1 (0x00007f6b366fd000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f6b36400000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f6b366cf000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f6b36000000)
	libcpr.so.1 => not found
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f6b36319000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f6b36724000)
```

**Comment by offa** [comment]
Strange … We both do exact the same steps, but get different results.
I've tested again: The error is reproducible on *master* but using the branch (same change as you did) works every time.

Is the ldd output complete? I do have a longer list, but those are system libs only – libcurl is included btw..

**Comment by s1m0n-f** [comment]
Hello!

I've tried again and it still does not work. I attached the terminal output as  .txt file if that could help. Now I tried on Ubuntu 23 instead using g++ 12. If I manually set LD_LIBRARY_PATH with `export LD_LIBRARY_PATH=/tmp/ifdbcxx_repro/deps/lib` and then run the test_package file it works. I find it really strange that you're not getting the same error. 

I tried installing both cpr and this to the normal install directories as well and still had the same issue, but if I set LD_LIBRARY_PATH to /usr/local/lib it worked.

[log.txt](https://github.com/offa/influxdb-cxx/files/11865565/log.txt)

**Comment by offa** [comment]
I was able to reproduce the issue on Ubuntu 22.04.2 based Github Action runners. :+1: 

This is interesting, since the images used for testing above – that did fail on *master* only – are Ubuntu too.

**Comment by offa** [comment]
Calling `ldconfig` after installation of cpr solves the issue (on both branches).

**Comment by offa** [comment]
I have merged the branch mentioned above. While not a solution for everything, it still fixes some issues.

**Comment by offa** [comment]
@s1m0n-f were you able to resolve the issue?

**Comment by s1m0n-f** [comment]
Yes, running ldconfig solved the problem for me as well, thanks for the help!
